# Generated by Django 5.0.4 on 2024-05-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_alter_students_niveau'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='students',
            name='matieres',
            field=models.ManyToManyField(to='schoolapp.matiere'),
        ),
    ]
