# Generated by Django 5.0.4 on 2024-05-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_professeur_remove_students_matieres_delete_matiere'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('period', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='professeur',
            name='matiere',
            field=models.CharField(choices=[('mathematiques', 'Mathématiques'), ('francais', 'Français'), ('arabe', 'Arabe'), ('anglais', 'Anglais'), ('histoire_geo', 'Histoire Géographie'), ('sciences', 'Sciences'), ('ei', 'Education Islamique'), ('philo', 'Philosohpie')], max_length=30),
        ),
        migrations.AlterField(
            model_name='students',
            name='niveau',
            field=models.CharField(choices=[('CP', 'CP'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2'), ('6eme', '6ème'), ('1AC', '1 AC'), ('2AC', '2 AC'), ('3AC', '3 AC'), ('tronc-commun', 'Tronc Commun'), ('premiere', 'Première année BAC'), ('deuxieme', 'Deuxième année BAC')], max_length=20),
        ),
    ]
